services:
  - type: web
    name: moodmagic-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import secrets; print(f'JWT_SECRET={secrets.token_urlsafe(32)}')" > .env
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: MoodMagic
      - key: APP_ENV
        value: production
      - key: BASE_URL
        value: https://moodmagic.onrender.com
      - key: OPENAI_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: moodmagic-db
          property: connectionString
      - key: CORS_ORIGINS
        value: https://moodmagic.app,http://localhost:3000,https://moodmagic.onrender.com
      - key: PORT
        value: 10000

databases:
  - name: moodmagic-db
    databaseName: moodmagic
    user: moodmagic
    plan: free 