services:
  - type: web
    name: moodmagic-api
    env: python
    region: oregon  # Choose the region closest to your users
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: APP_NAME
        value: MoodMagic
      - key: APP_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: SERPAPI_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: moodmagic-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        value: https://moodmagic.app,http://localhost:3000

databases:
  - name: moodmagic-db
    databaseName: moodmagic
    user: moodmagic
    plan: free  # Upgrade to higher tier for production 
    